# Application
spring.application.name=vendas-escolares

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/vendas_escolares
spring.datasource.username=postgres
spring.datasource.password=diego13633
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=minha-chave-super-secreta-para-jwt-que-precisa-ter-pelo-menos-64-caracteres-aqui123
jwt.expiration=86400000

# Server
server.port=8080